In [18]:
import requests
from bs4 import BeautifulSoup

r=requests.get("https://pythonizing.github.io/data/real-estate/rock-springs-wy/LCWYROCKSPRINGS/")
c=r.content

soup=BeautifulSoup(c,"html.parser")
#print(soup.prettify())

all=soup.find_all("div",{"class":"propertyRow"})
#all[0].find("h4",{"class":"propPrice"}).text.replace("\n","").replace(" ","")

In [55]:
l=[]
for item in all:
    d={}
    d["Price"]=item.find("h4",{"class","propPrice"}).text.replace("\n","").replace(" ","")
    d["Address"]=item.find_all("span",{"class","propAddressCollapse"})[0].text
    d["Locality"]=item.find_all("span",{"class","propAddressCollapse"})[1].text
    try:
          d["Beds"]=item.find("span",{"class","infoBed"}.text)
          
    except:
          d["Beds"]=None
    try:
          d["Area"]=item.find("span",{"class","infosqft"}).find("b").text
    except:
          d["Area"]=None
    try:
          d["Full Baths"]=item.find("span",{"class","infovaluefullBath"}).find("b").text
    except:
          d["Full Baths"]=None
    try:
          d["Half Baths"]=item.find("span",{"class","infovalueHalfBath"}).find("b").text
    except:
          d["Half Baths"]=None
    
    for column_group in item.find_all("div",{"class": "columnGroup"}):
          for feature_group,feature_name in zip(column_group.find_all("span",{"class": "featureGroup"}),column_group.find_all("span",{"class":"featureName"})):
              if "Lot Size" in feature_group.text:
                  d["Lot Size"]=feature_name.text
    l.append(d)

In [57]:
import pandas
df=pandas.DataFrame(l)
df

,Price,Address,Locality,Beds,Area,Full Baths,Half Baths,Lot Size
0,"$725,000",0 Gateway,"Rock Springs, WY 82901",None,None,None,None,NaN
1,"$452,900",1003 Winchester Blvd.,"Rock Springs, WY 82901",None,None,None,None,0.21 Acres
2,"$396,900",600 Talladega,"Rock Springs, WY 82901",None,None,None,None,NaN
3,"$389,900",3239 Spearhead Way,"Rock Springs, WY 82901",None,None,None,None,"Under 1/2 Acre,"
4,"$254,000",522 Emerald Street,"Rock Springs, WY 82901",None,None,None,None,"Under 1/2 Acre,"
5,"$252,900",1302 Veteran's Drive,"Rock Springs, WY 82901",None,None,None,None,0.27 Acres
6,"$210,000",1021 Cypress Cir,"Rock Springs, WY 82901",None,None,None,None,"Under 1/2 Acre,"
7,"$209,000",913 Madison Dr,"Rock Springs, WY 82901",None,None,None,None,"Under 1/2 Acre,"
8,"$199,900",1344 Teton Street,"Rock Springs, WY 82901",None,None,None,None,"Under 1/2 Acre,"
9,"$196,900",4 Minnies Lane,"Rock Springs, WY 82901",None,None,None,None,2.02 Acres

In [58]:
df.to_csv("Output.csv")